name: Tests
on:
  push:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - run: pip install ruff
      - run: |
          ruff format --check
          ruff check

  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest]
        qt: ["PySide6"]
        include:
          # Also try Mac and Windows, but just with the most common options:
          - os: macos-latest
            python: "3.13"
            qt: PySide6
          - os: windows-latest
            python: "3.13"
            qt: PySide6
          # Also try other Qt packages, but just with the easiest OS and common Python version:
          - os: ubuntu-latest
            python: "3.13"
            qt: "PyQt6"
          - os: ubuntu-latest
            python: "3.13"
            qt: "PyQt5"

    runs-on: ${{ matrix.os }}

    env:
      # Allow Qt to run without rendering anything
      QT_QPA_PLATFORM: "offscreen"
      XDG_RUNTIME_DIR: "/tmp/runtime-root"
      # Force Qt test with a particular version:
      PYTEST_QT_API: ${{ matrix.qt }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - run: pip install build twine pytest pytest-qt ${{ matrix.qt }}
      - run: python -m build .
      - run: twine check dist/*

      - run: pip install dist/*.whl
        shell: bash

      - name: Install Qt system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y libegl1 libxkbcommon-x11-0
        # We need quite some packages for `pytest-qt` to run without problems

      - run: pytest

      - uses: actions/upload-artifact@v6
        if: matrix.qt == 'PySide6'
        with:
          name: dist ${{ matrix.os }} ${{ matrix.python }}
          path: dist/

  deploy:
    needs: [build_and_test, linting]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: dist ubuntu-latest 3.13
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
